import {
  LayoutDashboard,
  Package,
  Store,
  Truck,
  Route,
  BarChart3,
} from "lucide-react";
import type { Role, Order, RouteData, Persona } from "./types";

export const initialOrders: Order[] = [
  {
    id: "WP-2041",
    name: "Fresh · Colombo 03",
    brand: "Fresh",
    district: "Colombo",
    amount: "640 kg",
    volume: "4.2 m³",
    window: "06:00 - 07:30",
    temp: "Chilled",
    status: "In transit",
    eta: "06:42",
    vehicle: "WP-012",
    access: "Rear dock",
  },
  {
    id: "WP-2042",
    name: "Fresh · Nugegoda",
    brand: "Fresh",
    district: "Colombo",
    amount: "420 kg",
    volume: "3.1 m³",
    window: "06:00 - 08:00",
    temp: "Ambient",
    status: "Delivered",
    eta: "06:18",
    vehicle: "WP-008",
    access: "Street",
  },
  {
    id: "WP-2043",
    name: "Style · Colombo City Centre",
    brand: "Style",
    district: "Colombo",
    amount: "280 kg",
    volume: "12.6 m³",
    window: "09:00 - 10:30",
    temp: "Ambient",
    status: "At risk",
    eta: "10:42",
    vehicle: "WP-024",
    access: "Mall bay",
  },
  {
    id: "WP-2044",
    name: "Tech · Kandy",
    brand: "Tech",
    district: "Kandy",
    amount: "980 kg",
    volume: "6.8 m³",
    window: "10:00 - 14:00",
    temp: "Ambient",
    status: "Scheduled",
    eta: "11:15",
    vehicle: "WP-041",
    access: "Rear dock",
  },
  {
    id: "WP-2045",
    name: "Fresh · Kadawatha",
    brand: "Fresh",
    district: "Gampaha",
    amount: "320 kg",
    volume: "2.4 m³",
    window: "05:30 - 07:45",
    temp: "Chilled",
    status: "Deferred",
    eta: "Next run",
    vehicle: "Unassigned",
    access: "Van only",
  },
  {
    id: "WP-2046",
    name: "Fresh · Wattala",
    brand: "Fresh",
    district: "Gampaha",
    amount: "510 kg",
    volume: "3.6 m³",
    window: "05:30 - 07:45",
    temp: "Chilled",
    status: "Scheduled",
    eta: "07:10",
    vehicle: "WP-016",
    access: "Rear dock",
  },
];
export const routes: RouteData[] = [
  {
    id: "R-012",
    name: "Colombo morning run",
    vehicle: "WP-012",
    driver: "Kasun Perera",
    initials: "KP",
    color: "#e97c49",
    stops: 6,
    done: 3,
    eta: "06:42",
    brand: "Fresh",
    type: "Refrigerated truck",
    depot: "Peliyagoda",
    weight: 68,
    volume: 74,
    fuel: 62,
    points: "162,229 210,244 239,293 221,346 275,380",
  },
  {
    id: "R-024",
    name: "City retail loop",
    vehicle: "WP-024",
    driver: "Nimal Silva",
    initials: "NS",
    color: "#76896a",
    stops: 4,
    done: 1,
    eta: "10:42",
    brand: "Style",
    type: "Dry-box truck",
    depot: "Peliyagoda",
    weight: 34,
    volume: 88,
    fuel: 54,
    points: "162,229 271,216 322,267 373,304",
  },
  {
    id: "R-041",
    name: "Kandy highland run",
    vehicle: "WP-041",
    driver: "Dilan Fernando",
    initials: "DF",
    color: "#8a88b2",
    stops: 5,
    done: 2,
    eta: "11:15",
    brand: "Tech",
    type: "Dry-box truck",
    depot: "Kandy",
    weight: 81,
    volume: 56,
    fuel: 73,
    points: "530,146 479,179 514,224 582,263",
  },
];
export const nav = [
  { label: "Overview", icon: LayoutDashboard },
  { label: "Dispatch planner", icon: Route },
  { label: "Orders", icon: Package },
  { label: "Fleet & drivers", icon: Truck },
  { label: "Outlets", icon: Store },
  { label: "Insights", icon: BarChart3 },
];
export const roleInfo: Record<Role, Persona> = {
  Dispatcher: {
    name: "Amaya",
    full: "Amaya Jayasinghe",
    initials: "AJ",
    title: "Network dispatcher",
  },
  Loader: {
    name: "Ruwan",
    full: "Ruwan Kumara",
    initials: "RK",
    title: "Warehouse loader",
  },
  Driver: {
    name: "Kasun",
    full: "Kasun Perera",
    initials: "KP",
    title: "Delivery driver",
  },
  "Store manager": {
    name: "Anjali",
    full: "Anjali Fernando",
    initials: "AF",
    title: "Store manager",
  },
};
